[package]
name = "fusor"
description = "placeholder"
version = "0.0.2"
authors = ["trashbyte <github@trashbyte.io>"]
edition = "2018"
license = "MIT"
repository = "https://github.com/trashbyte/fusor"
readme = "README.md"
keywords = []
categories = []

[dependencies]
